country_info = {
    "Afghanistan": "Afghanistan",
    "African Union": ["Algeria", "Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cape Verde", 
                      "Cameroon", "Central African Republic", "Chad", "Comoros", "Congo", "Democratic Republic of Congo", 
                      "Djibouti", "Egypt", "Equatorial Guinea", "Eritrea", "Eswatini", "Ethiopia", "Gabon", "Gambia", 
                      "Ghana", "Guinea", "Guinea-Bissau", "Ivory Coast", "Kenya", "Lesotho", "Liberia", "Libya", 
                      "Madagascar", "Malawi", "Mali", "Mauritania", "Mauritius", "Morocco", "Mozambique", "Namibia", 
                      "Niger", "Nigeria", "Rwanda", "Sahrawi Arab Democratic Republic", "São Tomé and Príncipe", "Senegal", 
                      "Seychelles", "Sierra Leone", "Somalia", "South Africa", "South Sudan", "Sudan", "Tanzania", "Togo", 
                      "Tunisia", "Uganda", "Zambia", "Zimbabwe"],
    "Albania": "Albania",
    "Algeria": "Algeria",
    "Anglosphere": ["United States", "United Kingdom", "Canada", "Australia", "New Zealand", "Ireland", "South Africa"],
    "Angola": "Angola",
    "Anhui": "China",
    "Antigua and Barbuda": "Antigua and Barbuda",
    "Argentina": "Argentina",
    "ASEAN": ["Brunei", "Cambodia", "Indonesia", "Laos", "Malaysia", "Myanmar", "Philippines", "Singapore", "Thailand", "Vietnam"],
    "Australia": "Australia",
    "Austria": "Austria",
    "Bahrain": "Bahrain",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Beijing": "China",
    "Belarus": "Belarus",
    "Belgium": "Belgium",
    "Bolivia": "Bolivia",
    "Botswana": "Botswana",
    "Brazil": "Brazil",
    "Bulgaria": "Bulgaria",
    "Burundi": "Burundi",
    "Cambodia": "Cambodia",
    "Cameroon": "Cameroon",
    "Canada": "Canada",
    "Chad": "Chad",
    "Chile": "Chile",
    "China": "China",
    "Chongqing": "China",
    "Colombia": "Colombia",
    "Costa Rica": "Costa Rica",
    "Croatia": "Croatia",
    "Cuba": "Cuba",
    "Cyprus": "Cyprus",
    "Czech Republic": "Czech Republic",
    "Democratic Republic of Congo": "Democratic Republic of Congo",
    "Denmark": "Denmark",
    "Djibouti": "Djibouti",
    "Dominican Republic": "Dominican Republic",
    "East African Community": ["Burundi", "Kenya", "Rwanda", "South Sudan", "Tanzania", "Uganda"],
    "Ecuador": "Ecuador",
    "Egypt": "Egypt",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Equatorial Guinea",
    "Eritrea": "Eritrea",
    "Estonia": "Estonia",
    "Ethiopia": "Ethiopia",
    "European Union": ["Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Czech Republic", "Denmark", "Estonia", 
                       "Finland", "France", "Germany", "Greece", "Hungary", "Ireland", "Italy", "Latvia", "Lithuania", 
                       "Luxembourg", "Malta", "Netherlands", "Poland", "Portugal", "Romania", "Slovakia", "Slovenia", 
                       "Spain", "Sweden"],
    "EU": ["Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Czech Republic", "Denmark", "Estonia", 
                       "Finland", "France", "Germany", "Greece", "Hungary", "Ireland", "Italy", "Latvia", "Lithuania", 
                       "Luxembourg", "Malta", "Netherlands", "Poland", "Portugal", "Romania", "Slovakia", "Slovenia", 
                       "Spain", "Sweden"],
    "Fiji": "Fiji",
    "Finland": "Finland",
    "France": "France",
    "Fujian": "China",
    "Gambia": "Gambia",
    "Gansu": "China",
    "Germany": "Germany",
    "Ghana": "Ghana",
    "Greece": "Greece",
    "Grenada": "Grenada",
    "Guangdong": "China",
    "Guangxi": "China",
    "Guinea": "Guinea",
    "Guyana": "Guyana",
    "Hainan": "China",
    "Heilongjiang": "China",
    "Henan": "China",
    "Hispanophone": ["Spain", "Hispanic America (various countries in Latin America where Spanish is spoken)"],
    "Hong Kong": "China",
    "Hubei": "China",
    "Hunan": "China",
    "Hungary": "Hungary",
    "Iceland": "Iceland",
    "India": "India",
    "Indonesia": "Indonesia",
    "Iran": "Iran",
    "Iraq": "Iraq",
    "Ireland": "Ireland",
    "Israel": "Israel",
    "Italy": "Italy",
    "Japan": "Japan",
    "Jiangsu": "China",
    "Jiangxi": "China",
    "Jilin": "China",
    "Jordan": "Jordan",
    "Kazakhstan": "Kazakhstan",
    "Kenya": "Kenya",
    "Kuwait": "Kuwait",
    "Kyrgyzstan": "Kyrgyzstan",
    "la Francophonie": ["France", "Belgium", "Switzerland", "Canada", "Madagascar", "Cameroon", "Ivory Coast", "Burkina Faso", "Niger", "Senegal", "Mali", "Rwanda", "Haiti", "Burundi", "Chad", "Togo", "Central African Republic", "Guinea", "Rwanda", "Seychelles", "Vanuatu", "Monaco", "Luxembourg", "Comoros", "Djibouti", "Equatorial Guinea", "Benin", "Congo", "Gabon", "Mauritius", "Morocco", "Tunisia", "Cambodia", "Laos", "Vietnam"],
    "Laos": "Laos",
    "Latvia": "Latvia",
    "Lebanon": "Lebanon",
    "Lesotho": "Lesotho",
    "Liberia": "Liberia",
    "Lithuania": "Lithuania",
    "Lusophone": ["Portugal", "Brazil", "Angola", "Mozambique", "Cape Verde", "Guinea-Bissau", "São Tomé and Príncipe", "East Timor"],
    "Malawi": "Malawi",
    "Malaysia": "Malaysia",
    "Maldives": "Maldives",
    "Mali": "Mali",
    "Malta": "Malta",
    "Mauritania": "Mauritania",
    "Mauritius": "Mauritius",
    "MENA": ["Algeria", "Bahrain", "Djibouti", "Egypt", "Iran", "Iraq", "Israel", "Jordan", "Kuwait", "Lebanon", "Libya", "Morocco", "Oman", "Qatar", "Saudi Arabia", "Syria", "Tunisia", "United Arab Emirates", "Yemen"],
    "Mexico": "Mexico",
    "Mongolia": "Mongolia",
    "Montenegro": "Montenegro",
    "Morocco": "Morocco",
    "Myanmar": "Myanmar",
    "Namibia": "Namibia",
    "Nepal": "Nepal",
    "Netherlands": "Netherlands",
    "New Zealand": "New Zealand",
    "Nigeria": "Nigeria",
    "North Macedonia": "North Macedonia",
    "Norway": "Norway",
    "Pakistan": "Pakistan",
    "Panama": "Panama",
    "Papua New Guinea": "Papua New Guinea",
    "Peru": "Peru",
    "Philippines": "Philippines",
    "Poland": "Poland",
    "Portugal": "Portugal",
    "Qatar": "Qatar",
    "Republic of Congo": "Republic of Congo",
    "Romania": "Romania",
    "Russia": "Russia",
    "Rwanda": "Rwanda",
    "Samoa": "Samoa",
    "São Tomé and Príncipe": "São Tomé and Príncipe",
    "Saudi Arabia": "Saudi Arabia",
    "Senegal": "Senegal",
    "Serbia": "Serbia",
    "Shaanxi": "China",
    "Shandong": "China",
    "Shanghai": "China",
    "Shanxi": "China",
    "Sichuan": "China",
    "Sierra Leone": "Sierra Leone",
    "Singapore": "Singapore",
    "Slovakia": "Slovakia",
    "Slovenia": "Slovenia",
    "Somalia": "Somalia",
    "South Africa": "South Africa",
    "South Korea": "South Korea",
    "South Sudan": "South Sudan",
    "Spain": "Spain",
    "Sri Lanka": "Sri Lanka",
    "Sudan": "Sudan",
    "Suriname": "Suriname",
    "Switzerland": "Switzerland",
    "Taiwan": "Taiwan",
    "Tanzania": "Tanzania",
    "Thailand": "Thailand",
    "Tibet": "China",
    "Tonga": "Tonga",
    "Trinidad and Tobago": "Trinidad and Tobago",
    "Türkiye": "Turkey",
    "UAE": "United Arab Emirates",
    "Uganda": "Uganda",
    "UK": "United Kingdom",
    "Ukraine": "Ukraine",
    "Uruguay": "Uruguay",
    "USA": "United States of America",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnam",
    "Xinjiang": "China",
    "Yemen": "Yemen",
    "Yunnan": "China",
    "Zhejiang": "China",
    "Zimbabwe": "Zimbabwe",
    "UN":["Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia",
        "Botswana",
        "Brazil",
        "Brunei",
        "Bulgaria",
        "Burkina",
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cape",
        "Central",
        "Chad",
        "Chile",
        "China",
        "Colombia",
        "Comoros",
        "Congo",
        "Costa",
        "CÃ´te",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czechia",
        "Democratic",
        "Democratic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican",
        "Ecuador",
        "Egypt",
        "El",
        "Equatorial",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Fiji",
        "Finland",
        "France",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Kuwait",
        "Kyrgyzstan",
        "Lao",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Micronesia",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Panama",
        "Papua",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Qatar",
        "Republic",
        "Republic",
        "Romania",
        "Russian",
        "Rwanda",
        "Saint",
        "Saint",
        "Saint",
        "Samoa",
        "San",
        "Sao",
        "Saudi",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon",
        "Somalia",
        "South",
        "South",
        "Spain",
        "Sri",
        "Sudan",
        "Suriname",
        "Swaziland",
        "Switzerland",
        "Sweden",
        "Syria",
        "Tajikistan",
        "Thailand",
        "The",
        "Timor",
        "Togo",
        "Tonga",
        "Trinidad",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United",
        "United",
        "United",
        "United",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Zambia",
        "Zimbabwe"]
}
